apiVersion: v1
kind: Service
metadata:
  name: golang-basic-server
  labels:
    app: basic-server
spec:
  selector:
    app: basic-server
  ports:
    - protocol: TCP
      name: golang-server-port
      port: 8090
      targetPort: 8090
