apiVersion: v1
kind: Service
metadata:
  name: golang-basic-server
  labels:
    app: basic-server
spec:
  type: NodePort
  selector:
    app: basic-server
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
